SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO I2 ON T.PARENT_ITEM_ID = I2.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NOT NULL
AND I2.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;