WITH RECURSIVE GENERATION_LOOP AS (
    SELECT E.ID, E.PARENT_ID, E.SIZE_OF_COLONY, E.DIFFERENTIATION_DATE, 1 AS GENERATION,
    CASE WHEN (SELECT COUNT(*) FROM ECOLI_DATA E2 WHERE E2.PARENT_ID = E.ID) > 0 THEN TRUE ELSE FALSE END AS CHILDREN
    FROM ECOLI_DATA E
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT E.ID, E.PARENT_ID, E.SIZE_OF_COLONY, E.DIFFERENTIATION_DATE, G.GENERATION + 1,
    CASE WHEN (SELECT COUNT(*) FROM ECOLI_DATA E2 WHERE E2.PARENT_ID = E.ID) > 0 THEN TRUE ELSE FALSE END AS CHILDREN
    FROM ECOLI_DATA E
    JOIN GENERATION_LOOP G ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, GENERATION FROM GENERATION_LOOP
WHERE CHILDREN = FALSE
GROUP BY GENERATION
ORDER BY GENERATION ASC;
