WITH FISH_LENGTH AS (
    SELECT ID, F.FISH_TYPE, LENGTH, TIME, FISH_NAME,
    MAX(LENGTH) OVER(PARTITION BY F.FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO I ON F.FISH_TYPE = I.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH FROM FISH_LENGTH
WHERE LENGTH = MAX_LENGTH
ORDER BY ID ASC;