WITH SORTED_DATA AS (
    SELECT *,
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTER
    FROM ECOLI_DATA
)
SELECT ID,
CASE
    WHEN QUARTER = 1 THEN 'CRITICAL'
    WHEN QUARTER = 2 THEN 'HIGH'
    WHEN QUARTER = 3 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM SORTED_DATA
ORDER BY ID ASC;